spring.application.name=fantacatalogo

# Profilo attivo di default quando lanci l'app dal PC senza Docker
spring.profiles.active=dev

# configurazioni del framework (impostazione su redirect)
server.forward-headers-strategy=framework