# Configurazione Database Locale (PC)
spring.datasource.url=jdbc:mysql://127.0.0.1:3308/fanta_db
spring.datasource.username=root
spring.datasource.password=fanta

# Config JPA
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true