spring.application.name=fantacatalogo

# Connessione al db
spring.datasource.url=jdbc:mysql://127.0.0.1:3308/fanta_db
spring.datasource.username=root
spring.datasource.password=fanta

# Config JPA
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# configurazioni del framework (impostazione su redirect)
server.forward-headers-strategy=framework

